spring:
  application:
    name: yourwriting

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://yw-database.c8cwxhg9hdfa.ap-northeast-2.rds.amazonaws.com/yw?serverTimezone=UTC&characterEncoding=UTF-8
    username: g16rim
    password: kr334404
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/realWriting?serverTimezone=UTC&characterEncoding=UTF-8
#    username: root
#    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true

jwt:
  token:
    secret: your-writing-secret-key
    validity-seconds: 25920000000 #초

cloud:
  aws:
    credentials:
      access-key: AKIAT373QO7SFI7IN6TM
      secret-key: hPnzQtkrJLfFesQBUA5lS6d76Xs7P07LBEoxg3wR
    stack.auto: false
    s3:
      bucket: yourwriting-bucket
    region:
      static: ap-northeast-2

file:
  list-max-size: 10485760 # 10MB
  list-max-count: 1
